title:             Autonomous Worlds Games
email:             froststarbook@gmail.com
description:       There are already quite a few full-chain games in existence. For example, within the StarkNet ecosystem, there is Loot-Survivor, and within the ETH ecosystem, there is Skystrife, among others (only one game is mentioned for each ecosystem).In order to collectively build the grand world of AW (Autonomous Worlds), after community discussions, it is now time to create a centralized website for full-chain games. This website will provide features such as game search, guides, tutorials, and more, allowing non-developers to immediately participate in the construction of AW.
author:            Frost
#url:               "localhost:4000"
url:               "https://chedaolabs.github.io/AutonomousWorldsGames/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
